# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190404_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='User',
            new_name='user',
        ),
    ]
