# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('new', 'New'), ('sale', 'Sale')], default='new', max_length=50),
        ),
    ]
