# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='before_discount_price',
        ),
    ]
